title: Xiaoyang Dai's Homepage
page-top-title: Xiaoyang Dai
top-section-bg-text: Be what you wanna be
home-subtitle: Xiaoyang Dai&ensp;|&ensp;Magicsaviors
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
